openapi: 3.0.0
info:
  title: Kanban Board API
  version: 1.0.0
  description: API documentation for Kanban Board application

servers:
  - url: http://localhost:3000/api
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT 